### ISSUE TITLE
Cannot find GOROOT directory on a self-hosted runner

### ISSUE THREAD

**Issue by ustiugov** [actions/setup-go#235]
**Description:**
Go setup fails on a self-hosted runner.
```
Setup go version spec 1.18
Found in cache @ /root/_work/_tool/go/1.18.2/x64
Added go to the path
go: cannot find GOROOT directory: $HOME/go
Error: Command failed: go env GOPATH
go: cannot find GOROOT directory: $HOME/go
```

**Action version:**
3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
1.18

**Repro steps:**  
[Full log](https://github.com/ease-lab/vhive/runs/6440960869?check_suite_focus=true#step:4:1)

**Comment by IvanZosimov** [comment]
Hello, @ustiugov 👋 Thank you for this issue, after investigation we'll get back to you with some results 😉

**Comment by IvanZosimov** [comment]
Hello again, @ustiugov 👋 The root cause of your problem hides in this [line](https://github.com/ease-lab/vhive/blob/main/.github/workflows/nightly_tests.yml#L14). Unfortunately, such syntax isn't supported for setting environment variables in the workflow files. Your workflow worked well because our [previous release of setup-go action](https://github.com/actions/setup-go/releases/tag/v3.0.0) set up the `GOROOT` environment variable after the installation process automatically and rewritten your setting. Now things were changed, we updated our action to this [release](https://github.com/actions/setup-go/releases/tag/v3.1.0) and got rid of the functionality for setting the `GOROOT` environment variable for GO versions higher than 1.9 (you can read about the reason [here](https://go.dev/doc/go1.9#goroot)) , that's why you got this error. To solve this issue you can just delete the above-mentioned line in your workflow file.

Cheers!

**Comment by ustiugov** [comment]
@IvanZosimov thanks! that worked

**Comment by IvanZosimov** [comment]
> @IvanZosimov thanks! that worked

You're most welcome!
