### ISSUE TITLE
apt install caching

### ISSUE THREAD

**Issue by JamesArthurHolland** [actions/setup-go#251]
**Description:**
Any chance we could utilise caching such as in this package:
https://github.com/marketplace/actions/cache-apt-packages

**Justification:**
Speed up builds and waste less build minutes.

**Are you willing to submit a PR?**
Yea I'll have a look if I have time.

**Comment by panticmilos** [comment]
Hi @JamesArthurHolland, thank you for submitting the issue, we will get back to you with more info ✌️

**Comment by panticmilos** [comment]
Hi @JamesArthurHolland,

After the discussion, we decided that we will not be implementing this feature, since it can be achieved with the `actions/cache` action. We don't want to increase the complexity of action if it can be achieved with other actions.

For that reason, I will close this issue now. If you feel like we need to discuss it more, feel free to continue the conversation here.
