### ISSUE TITLE
change 'stable' to exclude the first release, e.g not take 1.20.0

### ISSUE THREAD

**Issue by ldemailly** [actions/setup-go#327]
I don't want to use oldstable but I also am not insane and don't want to use just released go 1.20(.0)

can `stable` mean at least "not first release" ? ie 1.20.1 or even be changed manually when everything else works?

**Comment by panticmilos** [comment]
hi @ldemailly thank you for the report, we will take a look at it.

**Comment by ldemailly** [comment]
maybe an alternative so I can decide for an org what version is without changing 20 files in 10 projects would be can I reference the version from somewhere else (include) - I suppose a CI var at org level maybe?

**Comment by dmitry-shibanov** [comment]
Hello @ldemailly. Thank you for your feature request. We're not planing to implement this feature. For now Go does not have 1.20.1 version that is why it downloads 1.20.0 when you specify it as 1.20. To skip first release and download other patch versions you can specify go-version as ^1.20.1 but for now it won't work because 1.20.1 does not exist. 

For now I'm going to close the issue.

**Comment by ldemailly** [comment]
I was using "stable" not 1.20 and so it switched from 1.19.5 to 1.20.0 and my change request is to not move the "stable" label so quickly
