### ISSUE TITLE
setup-go does not pick up recent Go version leading to create vulnerable builds 

### ISSUE THREAD

**Issue by szuecs** [actions/setup-go#434]
**Description:**

The setup-go runs build with outdated Go version, even if there is a security vulnerability reported.
For us setup-go ran with Go-1.21.1 instead of Go-1.21.3.

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

latest release: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
latest commit in main: actions/setup-go@bfd2fb341f32be7281829126376a12a780ca79fc

both have the issue.

**Repro steps:**  

https://github.com/zalando/skipper/actions/runs/6536557643/job/17748524812#step:4:5

**Expected behavior:**

Invalidate the cache and run Go-1.21.3, once there is a new release of the Go runtime.

**Actual behavior:**

![image](https://github.com/actions/setup-go/assets/50872/7d02ba72-a071-4af6-ba1b-b21ed6b9836b)

```
Run actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
Setup go version spec ^1.20
Found in cache @ /opt/hostedtoolcache/go/1.21.1/x64
Added go to the path
Successfully set up Go version ^1.20
/opt/hostedtoolcache/go/1.21.1/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.21.1/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Cache is not found
go version go1.21.1 linux/amd64
```

**Work around**

https://github.com/zalando/skipper/pull/2688
set `check-latest: true`, which leads to:
```
Run go version
go version go1.21.3 linux/amd64
```

**Comment by dusan-trickovic** [comment]
Hello, @szuecs! Thank you for creating this issue, we will investigate it further and see what can be done :)

**Comment by dsame** [comment]
hello @szuecs ,

This is expected behaviour. According to the [README](https://github.com/actions/setup-go#v3)

```
The action will first check the local cache for a version match. If a version is not found locally ...
```

Checking for the other path versions would have unacceptably slowed down the builds. However, if it is critical to check setup-go for the most recent version, use the [check-latest](https://github.com/actions/setup-go#check-latest-version) input.

Alternatively, it is possible to set the desired version with the `go-version` input.

Did it help?

**Comment by szuecs** [comment]
@dsame the unexpected thing is the ttl. I would expect that either on change caches are invalidated or every time duration like every hour or every day.

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close the issue because the behaviour of the action was described in the [comment](https://github.com/actions/setup-go/issues/434#issuecomment-1814470282). The toolcache directory is updated during new images rollout and you can use `check-latest: true` to install Go from go-versions repository.

**Comment by adamdecaf** [comment]
Is there anything we can do to help merge PR's to go-versions? At $day_job we've had build failures for a few hours while waiting on a merge to go-versions. go-versions also does not have an issue tracker, so that's why I'm replying here.
