### ISSUE TITLE
Ever time I try to set it up it cancels work flow 

### ISSUE THREAD

**Issue by Tirzahgarcia** [actions/setup-go#482]
https://github.com/Tirzahgarcia/Tirzahgarcia/actions/runs/9327388380

**Comment by matthewhughes934** [comment]
The linked failure is on a run of `actions/setup-node@v3` as you configured here: https://github.com/Tirzahgarcia/Tirzahgarcia/blob/454299d8351498c8b67517d52ae8c1d8a59e24d2/.github/workflows/azure-webapps-node.yml#L40, the repo for that action is: https://github.com/actions/setup-node). This is the `actions/setup-go` repo

**Comment by priya-kinthali** [comment]
Hello @Tirzahgarcia 👋,
Thank you for raising this issue.
It looks like the error you are encountering is related to the `setup-node` action rather than the `setup-go` action. The error message indicates that a dependencies lock file (such as `package-lock.json`, `npm-shrinkwrap.json`, or `yarn.lock`) is not found in your repository's working directory. To resolve this issue, please ensure that you have one of the supported lock files (`package-lock.json`, `npm-shrinkwrap.json`, or `yarn.lock`) present in the root directory of your repository or the directory specified in your workflow. It is also important to commit this lock file to your repository to ensure consistent dependency management across different environments. For more details, please refer to the [setup-node documentation](https://github.com/actions/setup-node#caching-global-packages-data).

**Comment by priya-kinthali** [comment]
Hello @Tirzahgarcia!
As this error pertains to the `setup-node` action rather than the `setup-go` action, please consider raising this issue in the [setup-node repository](https://github.com/actions/setup-node) if you encounter any further problems.
We will proceed with closing this issue here. Thank you for your understanding:)
