### ISSUE TITLE
Cache restore fails with go 1.23

### ISSUE THREAD

**Issue by arodland** [actions/setup-go#506]
**Description:**

Cache restore is failing with a tar error whenever we build a project with go 1.23

**Action version:**
v5.0.2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
go 1.23.0

**Repro steps:**  

Build a repo with `go 1.23.0` in go.mod,

```yaml
uses: actions/setup-go@v5
with:
    go-version-file: go.mod
```

and an existing cache.

**Expected behavior:**
The cache is restored.

**Actual behavior:**
```
/usr/bin/tar -xf /home/runner/_work/_temp/af5c9c0c-c61a-4bbc-85b1-77654a640835/cache.tzst -P -C /home/runner/_work/quickset/quickset --use-compress-program unzstd
Received 530564234 of 530564234 (100.0%), 126.4 MBs/sec
/usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.31.0/config.json: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.31.0/LICENSE: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.31.0/go.mod: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.31.0/doc.go: Cannot open: File exists
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Cache is not found
go version go1.23.0 linux/amd64
```

**Comment by priya-kinthali** [comment]
Hello @arodland 👋,
Thank you for reporting this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by gowridurgad** [comment]
Hi @arodland, The issue you're facing during cache restoration is due to the telemetry update in Go 1.23.0. This update includes files (config.json, go.mod, LICENSE, doc.go) that already exist in the golang.org/x/telemetry directory, causing conflicts. When restoring the cache, these existing files prevent the tar command from completing successfully, resulting in "File exists" errors.

We have observed that the error related to extracting telemetry files is not present in Go version 1.23.1. Attached a screenshot for your reference This suggests that the issue might have been resolved in the newer release.
We recommend updating your workflow to use Go version 1.23.1 as follows:

```
- name: Set up Go
  uses: actions/setup-go@v5
  with:
    go-version: 1.23.1
```
If you continue to experience issues, please let us know.
<img width="1281" alt="Screenshot 2024-09-10 at 4 46 11 PM" src="https://github.com/user-attachments/assets/e562cf14-4a64-468c-babb-0c07ff6fe2f5">

**Comment by M4RC3L05** [comment]
Hey, I to have this problem on go v1.23.1:

```yaml
- name: setup go
  uses: actions/setup-go@v5
  with:
    go-version: 1.23.1
```

With this step on my workflow subsequent runs wont pickup the cache from previous runs.
I do not see any tar related errors.

first run (cache was saved): https://github.com/M4RC3L05/the-office-quote/actions/runs/11115162276/job/30883071608
seconds run (no cache hit): https://github.com/M4RC3L05/the-office-quote/actions/runs/11115251401/job/30883321848

**Comment by gowridurgad** [comment]
Hi @arodland, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by arodland** [comment]
I can confirm that the issue doesn't occur with go 1.23.1, and I suppose that's good enough. Closing.

**Comment by CodingTil** [comment]
Am I doing something wrong?

I have two sequential jobs, both using setup-go and doing some go stuff in the next step.

The first job successfully installs the specified go version (1.23.4 in my case), and then in the next step installs some dependencies.

The second job _also installs_ the go version, but recovers the dependencies from the cache -> the next step doesn't re-download the dependencies.

How come the dependencies are cached, but the go installation is not?

Also see: https://github.com/orgs/community/discussions/147802

**Comment by gowridurgad** [comment]
Hi @CodingTil, The reason your dependencies are cached but the Go installation is not, is due to the way the setup-go action handles caching:

- Dependencies are cached using the cache input parameter, which, when set to true, enables caching for Go dependencies.
- The Go installation is not cached by default and needs to be downloaded and installed for each job unless it's already available in the local tool cache.

For more details, you can check the  [documentation on caching dependencies](https://github.com/actions/setup-go/blob/3041bf56c941b39c61721a86cd11f3bb1338122a/docs/adrs/0000-caching-dependencies.md).
