### ISSUE TITLE
Copying wasm_exec.js from Go install 

### ISSUE THREAD

**Issue by adamdecaf** [actions/setup-go#71]
I was trying to build some WASM code and noticed `wasm_exec.js` doesn't seem to exist in the `GOROOT` directory tree. On Windows and macOS installs I can copy this file from `$(shell go env GOROOT)/misc/wasm/wasm_exec.js`. Does this file need to be explicitly copied from the distribution bundle? 

Example Actions run: https://github.com/moov-io/imagecashletter/runs/995953555?check_suite_focus=true

**Comment by adamdecaf** [comment]
Hey @Sergey-Murtazin currently we have to copy from the GOROOT, which is fine, but maybe the docs should mention this trick for WASM builds? 

https://github.com/moov-io/imagecashletter/blob/v0.7.0/makefile#L11-L14

**Comment by Sergey-Murtazin** [comment]
Hi, @adamdecaf!

Acording to tinygo [documentation](https://tinygo.org/docs/guides/webassembly/#building), you need to make sure that you have copied `wasm_exec.js` to your runtime environment

The information you ask to add to documentation is mostly related to tinygo compiler itself, not the `action/setup-go`.
That's why we wouldn't like to add it to README.

**Comment by adamdecaf** [comment]
I don't know what tinygo is and I was talking about the official Go compiler. Adding the docs into this readme could help folks who want to use the official Action, but if it's not wanted I understand.
